### ISSUE TITLE
determine what props for table

### ISSUE THREAD

**Issue by MilesHeise** [CodeForPittsburgh/food-access-map#13]
we have a table with a couple of random sample props. using either client input or our own logic we should determine which props from our dataset belong on the easy access table and reconfigure our table to display those props

**Comment by hellonewman** [comment]
These are my thoughts, will discuss with Sarah/PFPC:
    - Open days, hours (in some pretty format like "Open daily from 7am to 9pm")
    - Business type (supermarket, farmers market etc)
    - Accepts SNAP, accepts WIC
    - Address
        - Can we have a “get directions” link feature that would pull up Google Maps directions?

**Comment by MilesHeise** [comment]
quote from recent PR I sent covering some of this:

updates the table props to include requested items like address, place type, wic and snap. action button was added back in and can now navigate to google directions for the site. snap and wic render a checkbox full or empty based on true false. table starts default sorted by location type, partly so that an arrow will appear in the column making it more obvious you can sort columns with header clicks. directions button currently has a tooltip saying what it does, it looks like to add actual text below we have to override the action column manually, which is possible but a fair bit of work because we will have to replicate all of it (icon spacing, tooltips, onclick functionality, etc. there is no overriding just part of it . . .

**Comment by melynnduh** [comment]
Let's not bother adding the "get directions" text then unless we do user testing and find people don't know how to use the buttons. 

Talked with Sarah and confirmed that the props you have added are the ones she wants. We can close this!
