### ISSUE TITLE
make table clickable?

### ISSUE THREAD

**Issue by MilesHeise** [CodeForPittsburgh/food-access-map#21]
might be good if table items can be clicked to go to details page for that food site

**Comment by MilesHeise** [comment]
PR is in making this happen.

Currently this does it in 2 ways, we can leave both to keep it idiot proof or we can delete one and keep whichever one the client wants. the onRowClick prop makes it so that clicking anywhere on the row will send you, while the actions prop makes it so that there is an actions column with an icon button and tooltip that can send you there. if we decide we don't want one, only need to delete that prop, the rest of the architecture stays the same either way.

Once decision of one, other, or both is made, this issue can be closed

**Comment by hellonewman** [comment]
Clickable rows makes most sense to me- action buttons can be easy to miss.

**Comment by MilesHeise** [comment]
oh yeah, I think I already removed the other code and made this just clickable rows at some point and forgot to close the issue. cool :-)
